name: Livewire-todolist

on: 
  push:
    branches: 
      - master
  pull_request:
    branches:
    - master

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php_version: ['7.0', '7.1', '7.2', '7.3']
        
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install SQLite 3
        run: |
          sudo apt-get update
          sudo apt-get install sqlite3
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-6-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP ${{ matrix.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: |
         composer install --no-interaction --no-suggest --prefer-dist
         npm install
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
